### ISSUE TITLE
PyPi package creation/publication

### ISSUE THREAD

**Issue by clach04** [ActianCorp/sqlalchemy-ingres#11]
* bare minimum would be to use existing setup.py and publish via (say) https://pypi.org/project/twine
  * consider poetry/toml support - **might** make publishing easier

Related/linked issues issue #10, #11, #12, and #16.

Checklist:
- [x] update setup.py (see #11) with rename
- [x] delete setup.cfg
- [x] delete PKG-INFO
- [x] Add a license file, that matches meta data - FIX metadata to to APL2
- [x] more keywords/trove categories
- [x] package rename https://github.com/ActianCorp/sqlalchemy-ingres/issues/16
- [x] version information https://github.com/ActianCorp/sqlalchemy-ingres/issues/10
- [x] Doc updates for pip install from URL https://github.com/ActianCorp/sqlalchemy-ingres/issues/12

Experimental code:
  * https://github.com/ActianCorp/sqlalchemy-ingres/tree/issues_11_pypi_rename
  * https://pypi.org/project/sqlalchemy-ingres/0.0.4.dev1/

**Comment by clach04** [comment]
I'm currently thinking we stick with setup.py, especially if Jython support becomes important.

**Comment by clach04** [comment]
@hab6 I believe this is ready for testing, the following works for me:

    python -m pip install -e git+https://github.com/ActianCorp/sqlalchemy-ingres.git@issues_11_pypi_rename#egg=sqlalchemy-ingres

I'll likely do some polishing (doc wise, rather than fundamental changes) but ready now.

**Comment by clach04** [comment]
@hab6 Initial test dev version posted to https://pypi.org/project/sqlalchemy-ingres/0.0.4.dev1/

**Comment by hab6** [comment]
@clach04 Per your [comment](https://github.com/ActianCorp/sqlalchemy-ingres/issues/11#issuecomment-1911050826) I installed SQLAlchemy and the Ingres dialect with this command on Ubuntu

`python -m pip install -e git+https://github.com/ActianCorp/sqlalchemy-ingres.git@issues_11_pypi_rename#egg=sqlalchemy-ingres`

After also installing the Actian Client, I successfully ran a simple SQLAlchemy program to verify it worked. Excerpts from the program that worked:

     engine = sqlalchemy.create_engine(con_str)
     connection = engine.connect()
     query = 'SELECT * FROM iidbconstants'
     for row in connection.execute(sqlalchemy.text(query)):

**Comment by clach04** [comment]
Thanks @hab6 , did you get chance to install from PyPi?

    pip install sqlalchemy-ingres

**Comment by clach04** [comment]
Discussed with @hab6, testing works fine. I need to complete doc update then PR

**Comment by clach04** [comment]
Oddly enough, I can NOT see the README updates in the front page and the correct branch is selected, but opening readme directly I do see the changes made in https://github.com/ActianCorp/sqlalchemy-ingres/commit/9330078104b3159ebf665d5a6a936f3c3a4d0910
