### ISSUE TITLE
Document pip install option from git URL

### ISSUE THREAD

**Issue by clach04** [ActianCorp/sqlalchemy-ingres#12]
Current instructions https://github.com/ActianCorp/ingres_sa_dialect/blob/a6acefa5b4024c5d709c3078dba13c0eaf0f6a7b/README.md?plain=1#L53  (git clone and dev install) are currently for developers.

Document alternative:

    python -m pip install git+https://github.com/ActianCorp/ingres_sa_dialect.git

**Comment by clach04** [comment]
And for install from a branch:

    python -m pip install git+https://github.com/ActianCorp/ingres_sa_dialect.git@branch_name

**Comment by clach04** [comment]
@hab6 with current test results do you think it's work talking about a PyPi release? Cross reference with https://github.com/ActianCorp/ingres_sa_dialect/issues/16

**Comment by hab6** [comment]
@clach04 Yes, I think we should work toward updating https://pypi.org/ with a new Ingres dialect release given the current one out there is 14 years old!

**Comment by clach04** [comment]
A bunch of commits went in that tackle this via https://github.com/ActianCorp/sqlalchemy-ingres/issues/11, sadly non-tag #12. The PR could/should :-) 

See branch https://github.com/ActianCorp/sqlalchemy-ingres/tree/issues_11_pypi_rename

Relevant single Commit https://github.com/ActianCorp/sqlalchemy-ingres/commit/9330078104b3159ebf665d5a6a936f3c3a4d0910

**Comment by hab6** [comment]
@clach04 It looks like the following command doesn't work as given in the [sqlalchemy-ingres repository README](https://github.com/ActianCorp/sqlalchemy-ingres/#install-latest-from-github-without-a-source-code-checkout) and also documented on the [PyPi sqlalchemy-ingres page](https://pypi.org/project/sqlalchemy-ingres/).

`python -m pip install -e git+https://github.com/ActianCorp/sqlalchemy-ingres.git`

     python -m pip install -e git+https://github.com/ActianCorp/sqlalchemy-ingres.git
     ERROR: Could not detect requirement name for 
     'git+https://github.com/ActianCorp/sqlalchemy-ingres.git',
     please specify one with #egg=your_package_name

The documentation for [pip install](https://pip.pypa.io/en/stable/cli/pip_install/#examples) (`6. Install a project from VCS in “editable” mode`) shows adding the `#egg=name` syntax to explicitly state the project name.

With that change, it works:

```
(.venv) λ python -m pip install -e git+https://github.com/ActianCorp/sqlalchemy-ingres.git#egg=sqlalchemy-ingres
Obtaining sqlalchemy-ingres from git+https://github.com/ActianCorp/sqlalchemy-ingres.git#egg=sqlalchemy-ingres
  Updating c:\users\mhabiger\data\test\sqlalchemy\feb02\.venv\src\sqlalchemy-ingres clone
  Running command git fetch -q --tags
  Running command git reset --hard -q 6ebd23a20ae74f7f61d97e9fdce670e840c0b559
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting sqlalchemy (from sqlalchemy-ingres)
  Using cached SQLAlchemy-2.0.25-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\mhabiger\data\test\sqlalchemy\feb02\.venv\lib\site-packages (from sqlalchemy->sqlalchemy-ingres) (4.9.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\mhabiger\data\test\sqlalchemy\feb02\.venv\lib\site-packages (from sqlalchemy->sqlalchemy-ingres) (3.0.3)
Using cached SQLAlchemy-2.0.25-cp310-cp310-win_amd64.whl (2.1 MB)
Building wheels for collected packages: sqlalchemy-ingres
  Building editable for sqlalchemy-ingres (pyproject.toml) ... done
  Created wheel for sqlalchemy-ingres: filename=sqlalchemy_ingres-0.0.4.dev1-0.editable-py3-none-any.whl size=9493 sha256=2dd50eda7dbb8a7c5123b2e03c6ba4cd6c50cb35fdd4a027dd7146f4413cb11b
  Stored in directory: C:\Users\mhabiger\AppData\Local\Temp\pip-ephem-wheel-cache-rwk8aeih\wheels\40\e8\43\14bdd537d5250b9b399b56095b6b68dcc351b9c8464d8bab2c
Successfully built sqlalchemy-ingres
Installing collected packages: sqlalchemy, sqlalchemy-ingres
Successfully installed sqlalchemy-2.0.25 sqlalchemy-ingres-0.0.4.dev1
```

For the sake of comparison, it's worth mentioning (the obvious) that a non-editable installation command works without adding the `#egg=name`. i.e.

`(.venv) λ python -m pip install git+https://github.com/ActianCorp/sqlalchemy-ingres.git`

Could you double-check and confirm?

**Comment by clach04** [comment]
Quick update post chat today.

This definitely used to work, my guess is that it's a change to pip. I don't have a machine to hand to report back what version it was working with but off the top of my head 1.x or 2.x (laptop failures, hence not being sure). With hindsight we should maybe document pip versions that instructions have been tested with. I've never seen a change in behavior like this that took away a feature so there is a remote chance this is a pip bug?

This sort of goes away, as we discussed for some of my personal projects I have 3 sets of instructions:
1. pip install from pypi
2. pipi install from git URL so no need to checkout code explicitly, implicit checkout to get latest bleeding-edge code
3. git checkout and install from checkout.

What this is about is number 2, With pypi package almost ready (it's public now) that's likely to be the primary installation use case. So number 2 may have some asterisks !

**Comment by hab6** [comment]
I think this is completed. @clach04 Okay to close?
