### ISSUE TITLE
dependencies on driver

### ISSUE THREAD

**Issue by clach04** [ActianCorp/sqlalchemy-ingres#26]
Right now because we can in theory use any driver so hard coding pyodbc is not ideal.

Idea/proposal, use `extras_require` setup.py and implement pyodbc and pypyodbc (and leave the others missing, if anyone needs them we they can manually specify or send a PR).

Example:

    pip install "sqlalchemy-ingres[pyodbc]"
    pip install "sqlalchemy-ingres[pypyodbc]"
    pip install "sqlalchemy-ingres[pypyodbc,pyodbc]"
    pip install "sqlalchemy-ingres[all]"

See

  * https://setuptools.pypa.io/en/latest/userguide/dependency_management.html
  * https://stackoverflow.com/questions/41268863/what-is-the-difference-between-extras-require-and-install-requires-in-se

**Comment by hab6** [comment]
Delivered via #27
