### ISSUE TITLE
typo needs review in comment in README

### ISSUE THREAD

**Issue by clach04** [ActianCorp/sqlalchemy-ingres#34]
See https://github.com/ActianCorp/sqlalchemy-ingres/blob/master/README.md?plain=1#L165

This is not valid code if uncommented. Options:

1. change to `#import sqlalchemy_ingres` or `import sqlalchemy_ingres`
2. Remove.

@hab6 thoughts?

**Comment by hab6** [comment]
Completed via PR #38
